spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foo?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: 

  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    hibernate:
      show-sql: false
      
server:
    port: 8081      